name: puree_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  firebase_core: ^2.7.0
<<<<<<< HEAD
  google_sign_in: ^6.0.1
=======
  flutter_svg: ^0.17.1
  firebase_auth: ^4.2.9
  google_fonts: ^2.1.1
>>>>>>> front-end
  flutter:
    sdk: flutter
  firebase_auth: ^4.2.9
  hexcolor: ^3.0.1
  cloud_firestore: ^4.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/cloud.png
    - assets/images/cloud2.png
    - assets/images/logo.png
    - assets/images/logo.svg
    - assets/images/merchant_logo.png
    - google_fonts/
