// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAQSBznHXVx6kCuSj5lLsD76PJPTSkp-A',
    appId: '1:920578886432:web:18882cc4cbc45090e36545',
    messagingSenderId: '920578886432',
    projectId: 'puree-app',
    authDomain: 'puree-app.firebaseapp.com',
    storageBucket: 'puree-app.appspot.com',
    measurementId: 'G-HNZ30XS7M0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv6nUwCUC2IMqJu4i_uarVBAW0d3inNrk',
    appId: '1:920578886432:android:cbae9de5e3aab2f9e36545',
    messagingSenderId: '920578886432',
    projectId: 'puree-app',
    storageBucket: 'puree-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsd6i3IQWPM9ibSUJu1USdbnM2Q-7Wycw',
    appId: '1:920578886432:ios:39eeca9a096a05a0e36545',
    messagingSenderId: '920578886432',
    projectId: 'puree-app',
    storageBucket: 'puree-app.appspot.com',
    iosClientId:
        '920578886432-mngfqbogus8jir69jpt20u24n1f96iqh.apps.googleusercontent.com',
    iosBundleId: 'com.example.pureeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsd6i3IQWPM9ibSUJu1USdbnM2Q-7Wycw',
    appId: '1:920578886432:ios:39eeca9a096a05a0e36545',
    messagingSenderId: '920578886432',
    projectId: 'puree-app',
    storageBucket: 'puree-app.appspot.com',
    iosClientId:
        '920578886432-mngfqbogus8jir69jpt20u24n1f96iqh.apps.googleusercontent.com',
    iosBundleId: 'com.example.pureeApp',
  );
}
